title: Rongmei Literature Society
description: Rongmei language and literature resources.
theme: minima

sass:
  style: compressed

# Add custom styles to all pages (not just posts)
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      css: "/assets/css/style.css"
